name = "jsa-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jsa-db"
database_id = "9e0f50c0-e85b-4eef-a5e8-f5461965d823"
